# Generated by Django 4.2.6 on 2023-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0004_fabricante_pais_modeloauto_costo_fabricacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloauto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
