# Generated by Django 4.2.6 on 2023-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=3, verbose_name='Id')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Email')),
                ('designacion', models.CharField(max_length=150, verbose_name='Designación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actuialización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Employee',
            },
        ),
    ]
